title: Sarah Cole
description: Portfolio and Blog
theme: jekyll-theme-minimal
show_downloads: true

github:
  pub_url: https://scole024.github.io/the-mead-hall/publications/index.html
  viz_url: https://scole024.github.io/the-mead-hall/visualizations/index.html
  blog_url: https://scole024.github.io/the-mead-hall/posts/index.html
